[window]
padding = { x = 6, y = 4 }
dynamic_padding = true
decorations = "Full"

[font]
size = 9

[font.normal]
family = "Iosevka Term Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Iosevka Term Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Term Nerd Font Mono"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
shell = "/run/current-system/sw/bin/bash"
