[window]
padding = { x = 6, y = 6 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "Iosevka Term Nerd Font Mono", style = "Regular" }
size = 11.5

[scrolling]
history = 10000

[cursor]
style = { shape = "Block", blinking = "On" }

[general]
live_config_reload = true

[colors.primary]
background = "#272E33"
foreground = "#d3c6aa"

[colors.normal]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
