#!/bin/sh

# basic settings
bspc config border_width 2
bspc config window_gap 10

bspc config automatic_scheme alternate

bspc config focused_border_color "#5e81ac"
bspc config normal_border_color "#3b4252"

# rules (optional)
bspc rule -a Gimp state=floating

# autostart
sxhkd &
picom &
feh --bg-fill --randomize /home/saven/Pictures/wallpapers &
polybar &
