set keymod Mod1

set border on

set statusbar off

set mouse true


bind Mod1-Return create

bind Mod1-q destroy

bind Mod1-j focusnext
bind Mod1-k focusprev

bind Mod1-h focusleft
bind Mod1-l focusright


bind Mod1-space layoutnext

bind Mod1-z zoom

bind Mod1-H resizeleft
bind Mod1-L resizeright
bind Mod1-K resizeup
bind Mod1-J resizedown

bind Mod1-Shift-q quit
