# Remove all default key bindings
unbind -a

# (optional but common) remove prefix-based default behavior
unbind C-b
set -g prefix None

# set colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",st-256color:Tc"
set -ga terminal-overrides ",*;RGB"
set -g mouse on
set -g set-clipboard on

# New prefix
set -g prefix C-Space
bind C-Space send-prefix

# Needed binds
bind d detach-client
bind r source-file ~/.tmux.conf \; display "reloaded"

# Panes
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind f display-popup

bind -n M-S split-window -v -c "#{pane_current_path}"
bind -n M-s split-window -h -c "#{pane_current_path}"

# Sessions
bind s display-popup -E "s"

# Split Navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# General Configuration
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-! select-window -t 1
bind -n M-@ select-window -t 2
bind -n M-# select-window -t 3
bind -n M-$ select-window -t 4
bind -n M-% select-window -t 5
bind -n M-^ select-window -t 6
bind -n M-& select-window -t 7
bind -n M-* select-window -t 8
bind -n M-( select-window -t 9

bind t new-window

bind -n M-q kill-pane

# Vi copy mode
set-window-option -g mode-keys vi
bind c copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

unbind -T copy-mode-vi MouseDragEnd1Pane
