env=QT_QPA_PLATFORM,wayland
env=EDITOR,nvim
env=TERMINAL,alacritty
exec-once = noctalia
exec-once = firefox

cursor_theme=Bibata-Modern-Ice
cursor_size=24

env=XCURSOR_THEME,Bibata-Modern-Ice
env=XCURSOR_SIZE,24


gappih=5
gappiv=5
gappoh=5
gappov=5


default_mfact=0.5

xkb_rules_options=ctrl:nocaps

bind=SUPER,Return,spawn,alacritty

# bind=Alt,Space,spawn,rofi -show drun
bind=Alt,Space,spawn,noctalia msg panel-toggle launcher

bind=SUPER,Q,killclient

bind=SUPER+SHIFT,R,reload_config

bind=SUPER+SHIFT,Q,spawn_shell,/home/saven/nixos-config/dotfiles/scripts/power-menu-wayland.sh

bind=SUPER,B,spawn_shell,brightnessctl set +5%
bind=SUPER+SHIFT,B,spawn_shell,brightnessctl set 5%-

bind=SUPER,V,spawn_shell,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+
bind=SUPER+SHIFT,V,spawn_shell,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-

bind=SUPER,J,focusstack,next
bind=SUPER,K,focusstack,prev

bind=SUPER,L,exchange_stack_client,next
bind=SUPER,H,exchange_stack_client,prev

bordercolor=0x1E2326ff
focuscolor=0xA7C080ff

animations=1

animation_duration_open=200
animation_duration_close=200
animation_duration_move=200
animation_duration_tag=200
animation_duration_focus=0

animation_type_open=zoom
animation_type_close=zoom

bind = SUPER+SHIFT,F,toggle-fullscreen

scroller_structs=0
scroller_default_proportion=1.0
scroller_proportion_preset=0.5,1.0
new_is_master=0

bind=SUPER,T,setlayout,tile
bind=SUPER,S,setlayout,scroller
bind=SUPER,M,switch_proportion_preset

bind=SUPER,A,focusmonitor,prev
bind=SUPER,D,focusmonitor,next

bind=SUPER+SHIFT,A,tagmon,prev
bind=SUPER+SHIFT,D,tagmon,next

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
